all_schedule_str = "Все расписание"
next_lesson_str = "Cледующая пара"
todays_shedule_str = "Расписание на сегодня"
tommorow_shedule_str = "Расписание на завтра"
personal_schedule_str = "Личное расписание"
group_schedule_str = "Расписание группы"

cancel_str = "Отмена"
yes_str = "Да"
no_str = "Нет"
back_to_menu_str = "Вернуться на главное меню"

discover_free_time_str = "Узнать свободное время"
rating_str = "Расчитать итоговую оценку"
alert_str = "Настройка уведомлений"
find_group_str = "Найти группу"
register_str = "Регистрация"
keys_str = "У меня есть ключ"

change_sched_str = "Изменить расписание"
add_lesson_str = "Добавить урок"
delete_lesson_str = "Убрать урок"
replace_lesson_str = "Заменить урок"

configuration_str = "Настройки аккаунта"
whose_schedule_str = "Тип расписания"
